version: "3.9"

services:

  # Auth Service + DB
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./AuthService
    container_name: auth-service
    depends_on:
      - auth-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MS: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXP}

  # User Service + DB
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: useridb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  user-service:
    build: ./UserService
    container_name: user-service
    depends_on:
      - user-db
      - auth-service
      - redis
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/useridb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  # Order Service + DB
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: orderidb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  order-service:
    build: ./OrderService
    container_name: order-service
    depends_on:
      - order-db
      - user-service
      - auth-service
      - wiremock
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderidb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      USER_SERVICE_URL: http://user-service:8082
      AUTH_SERVICE_URL: http://auth-service:8081
      JWT_SECRET: ${JWT_SECRET}

    # Payment Service + DB
  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: paymentsidb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    depends_on:
      - payment-db
      - kafka
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/paymentsidb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      API_URL: https://random-data-api.com
      API_PATH: /api/number/random_number


  # API Gateway
  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - user-service
      - order-service
      - redis
    ports:
      - "8080:8080"
    environment:
      gateway.base: http://api-gateway:8080
      AUTH_SERVICE_URL: http://auth-service:8081
      USER_SERVICE_URL: http://user-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
      PAYMENT_SERVICE_URL: http://payment-service:8084
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

# Volumes
volumes:
  auth_pgdata:
  user_pgdata:
  order_pgdata:
  payment_pgdata: